/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // qfpaySidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  qfpaySidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index'
      },
      items: [
        'preparation/introduction', 
        'preparation/environments',
      ]
    },        
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'generated-index' },
      items: [
        'api-reference/request-format',
        'api-reference/response-format',
        'api-reference/signature-generation',            
        'api-reference/paytypes',
        'api-reference/currencies',
        'api-reference/status-codes',
        'api-reference/api-usage-guidelines',

      ]
    },
    {
      type: 'category',
      label: 'In-Store Payments',
      link: {
        type: 'generated-index'
      },
      items: [
        'in-store/MPM', 
        'in-store/CPM',
        {
          type: 'category',
          label: 'POS API',
          link: {
            type: 'generated-index'
          },
          items: [
            {
              type: 'doc',
              label: 'ECR',
              id:'in-store/pos-api/ECR'
            },
            {
              type: 'doc',
              label: 'App call App',
              id:'in-store/pos-api/app-call-app'
            },
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Online Payments',
      link: {
        type: 'generated-index'
      },
      items: [
        {
          type: 'category',
          label: 'Checkout Integration',
          link: {
            type: 'generated-index'
          },
          items: [
            "online-shop/checkout-integration/checkout",
            "online-shop/checkout-integration/payment-element"
          ]
        },
        {
          type: 'category',
          label: 'Integration by Payment Types',
          link: {
            type: 'generated-index'
          },
          items: [
            'online-shop/integration-by-payment-types/preauth',
            'online-shop/integration-by-payment-types/qfpay-recurring-payment',
            'online-shop/integration-by-payment-types/visa-master-online-payment',
            'online-shop/integration-by-payment-types/wap-payment',
            'online-shop/integration-by-payment-types/web-payment',
            'online-shop/integration-by-payment-types/in-app-payment',
            'online-shop/integration-by-payment-types/applepay',
            {
              type: 'category',
              label: 'Wechat',
              link: {
                type: 'generated-index'
              },
              items: [
                'online-shop/integration-by-payment-types/wechat/wechat-web-qrc-payments',
                'online-shop/integration-by-payment-types/wechat/wechat-pay-jsapi',
                'online-shop/integration-by-payment-types/wechat/wechat-pay-h5',
                'online-shop/integration-by-payment-types/wechat/wechat-mini-programs',
                'online-shop/integration-by-payment-types/wechat/wechat-in-app-payments',
              ]
            },
            {
              type: 'category',
              label: 'Alipay',
              link: {
                type: 'generated-index'
              },
              items: [
                'online-shop/integration-by-payment-types/alipay/alipay-online-payments', 
                'online-shop/integration-by-payment-types/alipay/alipay-service-window-h5',
                'online-shop/integration-by-payment-types/alipay/alipay-in-app-payments'
              ]
            },
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Shared Endpoints',
      link: {
        type: 'generated-index'
      },
      items: [
        'common-api/transaction-enquiry',
        'common-api/reversal-cancel',
        'common-api/refunds',
        'common-api/asynchronous-notification',
        'common-api/transaction-note'
      ]
    },
    'customs declaration',
    'FAQ',
  ],
   
};

export default sidebars;
